- name: Load the iptable_nat module (Fedora)
  when: 'ansible_os_family == "RedHat"'
  community.general.modprobe:
    name: iptable_nat
    persistent: present
- name: Make sure that the docker folders exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
    mode: '0644'
  loop:
    - "{{ docker_compose_dir }}"
    - "{{ docker_dir }}"

- name: Find service directories inside files
  ansible.builtin.find:
    paths: "{{ role_path }}/containers"
    file_type: directory
  register: services
  delegate_to: localhost
  become: false

- name: Set services list from folder names
  ansible.builtin.set_fact:
    services: "{{ services.files | map(attribute='path') | map('basename') | list | difference(disabled_services) }}"

- name: Create service-specific compose directories
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
    mode: '0644'
  loop: "{{ services }}"

- name: Create service-specific data directories
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
    mode: '0644'
  loop: "{{ services }}"


- name: Copy the compose file
  ansible.builtin.template:
    src: "containers/{{ item }}/compose.yml"
    dest: "{{ docker_compose_dir }}/{{ item }}/compose.yml"
    mode: '0644'
  loop: "{{ services }}"

- name: Copy Traefik files
  ansible.builtin.template:
    src: "templates/traefik/{{ item }}"
    dest: "{{ docker_compose_dir }}/traefik/{{ item }}"
    mode: '0644'
  loop:
    - traefik.yaml
  when: "'traefik' in services"

- name: Create acme.json if it doesn't exist
  ansible.builtin.file:
    path: "{{ docker_dir }}/traefik/acme.json"
    state: touch
    mode: '0600'
    owner: root
    group: root
  when: "'traefik' in services"

- name: Find env files
  ansible.builtin.find:
    paths: "{{ role_path }}/containers/{{ item }}"
    patterns: ".*"
    recurse: false
    hidden: true
  register: env_files
  delegate_to: localhost
  become: false
  loop: "{{ services }}"

- name: Set fact to create dictionary of env files
  ansible.builtin.set_fact:
    env_files_dict: >-
      {{
        env_files_dict | default({}) | combine({ item.item: item.files | map(attribute='path') | list })
      }}
  loop: "{{ env_files.results }}"

- name: Copy .env files to service-specific docker compose directory
  ansible.builtin.template:
    src: "{{ item.1.path }}"  # Access the path of each .env file
    dest: "{{ docker_compose_dir }}/{{ item.0.item }}/{{ item.1.path | basename }}"  # Copy to service-specific directory
    mode: '0644'
  with_subelements:
    - "{{ env_files.results }}"  # Loop over each service's find result
    - files  # Access the list of files from the find result
  when: item.1.path is defined  # Only copy if the file path is defined

- name: Docker-compose up
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}/{{ item }}"
    docker_cli: "/usr/bin/docker"
  loop: "{{ services }}"
