---
disabled_services:
  # - traefik
  - firefly
  - arr
  - wireguard
  - authentik
  - nginxproxymanager



# nextcloud
nextcloud_port: 11000
nextcloud_mysqluser: nextcloud
nextcloud_mysqldbhost: db

# restic
restic_backup_location: "/home/{{ username }}/restic"