---
services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    network_mode: 'host'
    environment:
      - PUID=1000
      - PGID=1000

    volumes:
      - "{{ docker_dir }}/ddclient/config.json:/config.json"
    restart: unless-stopped