---
# Playbook run file
- name: Server Config
  hosts: home
  gather_facts: true
  become: true
  roles:
    - role: system
      tags:
        - system

    - role: geerlingguy.docker
      tags:
        - docker

    # - role: geerlingguy.repo-epel

    - role: geerlingguy.security
      tags:
        - security

    - role: containers
      tags:
        - containers
