---
- name: Install Python and python3-pip
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
    state: present

# - name: Install docker module for Python
#   ansible.builtin.pip:
#     name:
#       - docker
#       - docker-compose

- name: Make sure that the docker folders exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
    mode: '0644'
  loop:
    - "{{ docker_compose_dir }}"
    - "{{ docker_dir }}"

- name: Copy the compose file
  ansible.builtin.template:
    src: templates/compose.yaml
    dest: "{{ docker_compose_dir }}/compose.yaml"
    mode: '0644'
  vars:
    app_cidr: "{{ (networks | selectattr('name', '==', 'app') | map(attribute='cidr') | first) | default('') }}"
    app_base: "{{ (networks | selectattr('name', '==', 'app') | map(attribute='base') | first) | default('') }}"

- name: Docker-compose up
  community.docker.docker_compose:
    project_src: "{{ docker_compose_dir }}"
