# Vars for the entire project
hostname: '{{ inventory_hostname }}'
timezone: Europe/Athens
locale: en_US.UTF-8
keyboard_layout: us
username: "{{ vault_username }}"
host_ip: "{{ vault_host_ip }}"
shell: /usr/bin/bash
# dotfiles_repo: https://github.com/ak0p/dotfiles
guid: 1000
ansible_port: 49872
security_ssh_port: 49872
ssh_public_key: "{{ vault_ssh_public_key }}"
ssh_private_key: "{{ vault_ssh_private_key }}"

networks:
  - name: lan
    cidr: 192.168.1.0/24
    base: 192.168.1
  - name: app
    cidr: 10.0.0.0/24
    base: 10.0.0

docker_dir: /opt/docker/data
docker_compose_dir: /opt/docker/compose

services:
  - nginxproxymanager
  - nextcloud
  - portainer
  # - photoprism
  - cloudflareddns
  - vaultwarden
  - wireguard

extra_packages:
  - iperf3
  - speedtest-cli
  - htop
  - git
  - neovim
  - tmux
  - fail2ban
  - lm_sensors
  - powertop
