---
networks:
    arr:
        name: arr

services:
    prowlarr:
        image: lscr.io/linuxserver/prowlarr:latest
        container_name: prowlarr
        environment:
        - PUID=1000
        - PGID=1000
        - TZ=Etc/UTC
        volumes:
        - /path/to/prowlarr/data:/config
        ports:
        - 9696:9696
        restart: unless-stopped
        networks:
            arr:

    sonarr:
        image: lscr.io/linuxserver/sonarr:latest
        container_name: sonarr
        environment:
        - PUID=1000
        - PGID=1000
        - TZ=Etc/UTC
        volumes:
        - /path/to/sonarr/data:/config
        - /path/to/tvseries:/tv #optional
        - /path/to/downloadclient-downloads:/downloads #optional
        ports:
        - 8989:8989
        restart: unless-stopped
        networks:
            arr:

    readarr:
        image: lscr.io/linuxserver/readarr:develop
        container_name: readarr
        environment:
        - PUID=1000
        - PGID=1000
        - TZ=Etc/UTC
        volumes:
        - /path/to/readarr/data:/config
        - /path/to/books:/books #optional
        - /path/to/download-client-downloads:/downloads #optional
        ports:
        - 8787:8787
        restart: unless-stopped
        networks:
            arr:

    deluge:
        image: lscr.io/linuxserver/deluge:latest
        container_name: deluge
        environment:
        - PUID=1000
        - PGID=1000
        - TZ=Etc/UTC
        - DELUGE_LOGLEVEL=error #optional
        volumes:
        - /path/to/deluge/config:/config
        - /path/to/downloads:/downloads
        ports:
        - 8112:8112
        - 6881:6881
        - 6881:6881/udp
        - 58846:58846 #optional
        restart: unless-stopped
        networks:
            arr:

    overseerr:
        image: lscr.io/linuxserver/overseerr:latest
        container_name: overseerr
        environment:
        - PUID=1000
        - PGID=1000
        - TZ=Etc/UTC
        volumes:
        - /path/to/overseerr/config:/config
        ports:
        - 5055:5055
        restart: unless-stopped
        networks:
            arr:

    bazarr:
        image: lscr.io/linuxserver/bazarr:latest
        container_name: bazarr
        environment:
        - PUID=1000
        - PGID=1000
        - TZ=Etc/UTC
        volumes:
        - /path/to/bazarr/config:/config
        - /path/to/movies:/movies #optional
        - /path/to/tv:/tv #optional
        ports:
        - 6767:6767
        restart: unless-stopped
