services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:4 # images are also available on docker hub: seriousm4x/upsnap:4
    # network_mode: host
    restart: unless-stopped
    volumes:
      - {{ docker_dir }}/upsnap/data:/app/pb_data
    networks:
      maclandefault:
        ipv4_address: 192.168.1.4
    environment:
      - TZ=Europe/Athens

networks:
  maclandefault:
    external:
      true
