---
home:
  hosts:
    raspberrypi:
      ansible_host: 192.168.1.179
      ansible_user: "{{ vault_username }}"
      ansible_password: "{{ vault_ansible_password }}"
      ansible_connection: ssh
      ansible_ssh_private_key_file: "{{ ssh_private_key }}"
      ansible_become_password: "{{ vault_ansible_password }}"
