---
- name: Update and upgrade packages
  ansible.builtin.dnf:
    update_cache: true
    name: "*"
    state: latest

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  ansible.builtin.reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists

- name: Install extra packages
  ansible.builtin.package:
    name: "{{ extra_packages }}"
    state: present

- name: Set the hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Replace the hostname entry with our own
  ansible.builtin.lineinfile:
    path: /etc/hosts
    insertafter: ^127\.0\.0\.1 *localhost
    line: "127.0.0.1 {{ inventory_hostname }}"
    owner: root
    group: root
    mode: '0644'

# - name: Disable cron e-mail notifications
#   cron:
#     name: MAILTO
#     user: root
#     env: yes
#     job: ""
